- flink-shaded-asm-5/packaged_licenses/LICENSE.asm.txt
- flink-shaded-netty-4/packaged_licenses/LICENSE.jauter.txt
- flink-shaded-netty-4/packaged_licenses/LICENSE.netty_router.txt
- pom.xml
Include non-Apache2 licenses in final jars.
> (#6) - Include licenses of shaded dependencies in jars

- flink-shaded-asm-5/pom.xml
- flink-shaded-guava-18/pom.xml
- flink-shaded-netty-4/pom.xml
This PR modifies the version schemes, so that the final artifact names look like this:
`flink-shaded-asm-5.0.4-1.0`.
This name does not contain an underscore before the dependency version, in contrast to the issue description, since maven uses a dash to separate artifactId and version.
> (#16) Simplify artifact version scheme

- flink-shaded-jackson-parent/flink-shaded-jackson-2/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-module-jsonSchema-2/pom.xml
- flink-shaded-jackson-parent/pom.xml
- pom.xml
This PR adds a second variant flink-shaded-jackson which also includes the jsonSchema module. Both variants now inherit from `flink-shaded-jackson-parent` which contains the shading configuration.
> (#31) Add extended flink-shadaed-jackson-module-jsonSchema module

- flink-shaded-netty-4/pom.xml
This is a part of [FLINK-3952](https://issues.apache.org/jira/browse/FLINK-3952)
> [FLINK-3952] Bump Netty to 4.1.24 and drop netty-router

- flink-shaded-asm-5/pom.xml
- flink-shaded-guava-18/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-2/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-module-jsonSchema-2/pom.xml
- flink-shaded-jackson-parent/pom.xml
- flink-shaded-netty-4/pom.xml
- tools/releasing/update_branch_version.sh
the previous commit, i.e. 49c9fa878cab53ab76f3e4302e4f48920566a2e2, did not adapt the sub-modules' version strings
> [FLINK-9817] update version to 5.0, part 2

- flink-shaded-netty-4/pom.xml
- flink-shaded-netty-4/src/main/resources/META-INF/NOTICE
Notable changes since 4.1.24:
- big improvements (performance, feature set) for using openSSL based
SSL engine (useful for FLINK-9816)
- allow multiple shaded versions of the same netty artifact (as long
as the shaded prefix is different)
- Ensure ByteToMessageDecoder.Cumulator implementations always release
- Don't re-arm timerfd each epoll_wait
- Use a non-volatile read for ensureAccessible() whenever possible to
reduce overhead and allow better inlining.
- Do not fail on runtime when an older version of Log4J2 is on the
classpath
- Fix leak and corruption bugs in CompositeByteBuf
- Add support for TLSv1.3
- Harden ref-counting concurrency semantics
- bug fixes
- Java 9-12 related fixes
- no license changes
- no changes in Netty's NOTICE file
Please note that this PR is based on #52 but …
> [FLINK-11154][network] bump Netty to 4.1.32

- flink-shaded-netty-tcnative-dynamic/pom.xml
- flink-shaded-netty-tcnative-dynamic/src/main/resources/META-INF/NOTICE
- flink-shaded-netty-tcnative-static/pom.xml
- flink-shaded-netty-tcnative-static/src/main/resources/META-INF/NOTICE
- pom.xml
This PR provides two variants of a shaded netty-tcnative artifact:
- one with native libraries which are dynamically linked to openSSL: `flink-shaded-netty-tcnative-dynamic`, and
- one with native libraries which are statically linked to boringSSL: `flink-shaded-netty-tcnative-static`
Since the built artifact from `flink-shaded-netty-tcnative-static` contains binaries made from files under the openSSL license, we do not build these by default but enable the user to do this on his own via:
```
mvn clean install -Pinclude-netty-tcnative-static
```
More information on the differences can be found here:
- https://netty.io/wiki/requirements-for-4.x.html#wiki-h4-4
- https://netty.io/wiki/forked-tomcat-native.html
> [FLINK-11580] Provide a shaded netty-tcnative

- flink-shaded-hadoop-2-uber/pom.xml
- flink-shaded-hadoop-2/pom.xml
In this PR will add ` dependency management` entries for `flink-shaded-hadoop`. 
Process of consideration:
1. DependencyList -> list all the dependency for `flink-shaded-hadoop` by `mvn dependency:tree`
2.  TargetDependencyList -> find out the `artifactId` both in `DependencyList` and `flink-parent's dependencyManagement`. 
3. add the `TargetDependencyList` into ` dependency management` of `flink-shaded-hadoop-2` in `flink-shaded`.
>  [FLINK-12515][Build System, BuildSystem / Shaded] Sync flink-shaded-hadoop with dependency management entries

- flink-shaded-hadoop-2/pom.xml
This PR adds `findfugs` and `slf4j-api` as a provided dependency.  the goal is to align the Flink master `flink-shaded-hadoop`did, as follows:
What do you think? @zentol
> [hotfix][hadoop] adds findfugs and slf4j-api as a provided dependency

- pom.xml
In contrast to #63, this one only updates the maven-shade-plugin for the shade-sources build profile.
This fixes a potential NPE (seems to appear only with some maven versions) when
trying to shade sources with a dependency being unavailable.
Steps to reproduce the previous error (using maven 3.6.1):
```
> mvn clean package -Pshade-sources
...
[INFO] --- maven-shade-plugin:3.0.0:shade (shade-flink) @ flink-shaded-hadoop-2 ---
[INFO] Excluding org.apache.commons:commons-compress:jar:1.18 from the shaded jar.
[INFO] Excluding org.apache.avro:avro:jar:1.8.2 from the shaded jar.
[INFO] Including org.codehaus.jackson:jackson-core-asl:jar:1.9.13 in the shaded jar.
[INFO] Including org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13 in the shaded jar.
[INFO] Excluding …
```
> [FLINK-12598] update maven-shade-plugin to version 3.1.1 for the shade-sources profile

- flink-shaded-hadoop-2/pom.xml
- pom.xml
`flink-shaded` equivalent to https://github.com/apache/flink/pull/9292.
> [FLINK-13455][build] Move jdk.tools exclusions out of dependency management

- flink-shaded-asm-7/pom.xml
- flink-shaded-asm-7/src/main/resources/META-INF/NOTICE
Includes asm-commons in flink-shaded-asm, as this is required for a rework of the serializer migration test base.
Additionally, contains a follow-up for FLINK-13467 which updates the major version in the NOTICE file, and a hotfix that simplifies future version bumps by relying on the `asm.major.version` property in the shading pattern.
> [FLINK-13720][asm] Include asm-commons

- flink-shaded-netty-4/pom.xml
- flink-shaded-netty-4/src/main/resources/META-INF/NOTICE
Below, you will find a list of bug fixes and performance improvements that may affect us. Nice
changes we could benefit from, also for the Java > 8 efforts. The most important ones fixing leaks etc are `#8921`, `#9167`, `#9274`, `#9394`, and the various `CompositeByteBuf` fixes. The rest are mostly performance improvements.
Also, it looks like Netty now supports Mac OS native `kqueue` transports in addition to `NIO` (all OS) and `epoll` (Linux). We could eventually enable this via `taskmanager.network.netty.transport` as well.
Since we are still early in the dev cycle for Flink 1.10, it would be nice to update now and verify that the new version works correctly.
```
Netty 4.1.33.Final
- Fix ClassCastException and native crash when using kqueue transport
(#8665)
- Provide a way to cache …
```
> [FLINK-13770][network] Bump Netty to 4.1.39.Final

- pom.xml
Pins the encoding for the `ApacheNoticeResourceTransformer`. Without this the transformer reads/writes all files using a platform-dependent encoding, which makes some parts of the build non-deterministic.
> [FLINK-14413][build] Specify encoding for ApacheNoticeResourceTransformer

- flink-shaded-jackson-parent/flink-shaded-jackson-2/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-2/src/main/resources/META-INF/NOTICE
- flink-shaded-jackson-parent/flink-shaded-jackson-module-jsonSchema-2/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-module-jsonSchema-2/src/main/resources/META-INF/NOTICE
- flink-shaded-jackson-parent/pom.xml
- pom.xml
This fixes the following vulnerabilities:
- CVE-2019-12384
- CVE-2019-12814
- CVE-2019-14379
- CVE-2019-14439
See https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apache/flink-shaded/72)
> [FLINK-14104][jackson] Bump up to version 2.9.9[.3]

- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-34/pom.xml
- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-34/src/main/resources/META-INF/NOTICE
- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-35/pom.xml
- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-35/src/main/resources/META-INF/NOTICE
- flink-shaded-zookeeper-parent/pom.xml
- pom.xml
Adds 2 new modules that bundle zookeeper (3.4.10/3.5.5) and curator-recipes (4.2.0). Both modules are self-contained and use the same shading pattern (required so that Flink can easily switch between them).
Both modules exclude most dependencies (based on the existing shading logic in the Flink master) and as a result only bundle apache-llicensed dependencies (yay!).
I have verified that these versions work with a modified Flink 1.11 against zookeeper 3.4.14 (with the 3.4 module) and 3.5.6 (with both modules).
A preview of the intended Flink setup can be found here: https://github.com/zentol/flink/tree/zk_cur
> [FLINK-15742][build] Add curator/zookeeper module

- flink-shaded-asm-7/pom.xml
- flink-shaded-guava-18/pom.xml
- flink-shaded-hadoop-2-parent/flink-shaded-hadoop-2-uber/pom.xml
- flink-shaded-hadoop-2-parent/flink-shaded-hadoop-2/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-2/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-module-jsonSchema-2/pom.xml
- flink-shaded-netty-4/pom.xml
- flink-shaded-netty-tcnative-dynamic/pom.xml
- flink-shaded-netty-tcnative-static/pom.xml
- flink-shaded-zookeeper-parent/pom.xml
- pom.xml
During the build process we rely on the `shade-plugin` to replace references to properties (e.g., `${scala.binary.version}`) by their actual value.
This is important because the property _field_ cannot be changed during the build. If you set a property on the command-line the _field_ is not updated, only the in-memory analogue is.
Hence any references to the property after the build process are problematic because you can have a value mismatch between the value set in the field vs the one set at build-time.
Turns out the shade-plugin does not resolve properties in the `<version>` field, resulting in an inconsistency which some build systems outright reject.
We now additionally use the `flatten-plugin` to resolve _all_ properties.
The primary purpose of this plugin is to create fully …
> [FLINK-16527][build] Resolve properties in version field

- flink-shaded-jackson-parent/flink-shaded-jackson-2/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-2/src/main/resources/META-INF/NOTICE
- flink-shaded-jackson-parent/flink-shaded-jackson-module-jsonSchema-2/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-module-jsonSchema-2/src/main/resources/META-INF/NOTICE
- flink-shaded-jackson-parent/pom.xml
This fixes the following vulnerability
https://nvd.nist.gov/vuln/detail/CVE-2020-25649
which has been fixed in 2.10.5.1
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10#micro-patches
In order not to release versions too frequently, so we upgrade the version of Jackson to 2.12.1.
> [FLINK-21020][jackson] Bump version to 2.12.1

- flink-shaded-netty-4/pom.xml
- flink-shaded-netty-4/src/main/resources/META-INF/NOTICE
- flink-shaded-netty-tcnative-dynamic/pom.xml
- flink-shaded-netty-tcnative-dynamic/src/main/resources/META-INF/NOTICE
- flink-shaded-netty-tcnative-static/pom.xml
- flink-shaded-netty-tcnative-static/src/main/resources/META-INF/NOTICE
Our shading setup for native bindings, which need to be bumped to 2.0.39, needed most of the changes.
- The netty files have been renamed, so I had to adjust our file matching & renaming.
- the dynamic windows binding appears to no longer exist 🤷 
- there's now a dynamic binding for ARM
- there's now a dynamic binding specific to Fedora Linux, which needs some special handling because the file name clash with the vanilla Linux one (voidig some of the benefits of renaming things in the first place...)
> [FLINK-23325] Bump netty to 4.1.65

- flink-shaded-guava-18/pom.xml
- flink-shaded-guava-18/src/main/resources/META-INF/NOTICE
A big dependency bump that was long overdue.
The `failureaccess` dependency is something that was previously part of guava, and now is a separate artifact.
They also tried something similar with `listenablefuture`, which apparently did not work out so well, and now they are stuck with an empty artifact in their dependency tree 🤦 .
> [FLINK-23326] Bump guava to 30.1.1-jre

- flink-shaded-jackson-parent/flink-shaded-jackson-2/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-2/src/main/resources/META-INF/NOTICE
- flink-shaded-jackson-parent/flink-shaded-jackson-module-jsonSchema-2/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-module-jsonSchema-2/src/main/resources/META-INF/NOTICE
- flink-shaded-jackson-parent/pom.xml
Bumps jackson and the contained snakeyaml. The updates are only fixing bugs; nothing security related afaict.
> [FLINK-23291] Bump jackson to 2.12.4 

- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-35/pom.xml
- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-35/src/main/resources/META-INF/NOTICE
Upgrades out ZK 3.5 dependency to the latest bugfix release. Contains both bug and security fixes.
ZK 3.5 is still a supported version, hence we're sticking with it for the time being instead of jumping to 3.6, which would also require a curator upgrade.
> [FLINK-23299] Bump Zookeeper to 3.5.9

- flink-shaded-netty-4/src/main/resources/META-INF/NOTICE
- flink-shaded-netty-tcnative-dynamic/pom.xml
- flink-shaded-netty-tcnative-dynamic/src/main/resources/META-INF/NOTICE
- flink-shaded-netty-tcnative-static/pom.xml
- flink-shaded-netty-tcnative-static/src/main/resources/META-INF/NOTICE
- pom.xml
CI run with Flink using the updated version: https://dev.azure.com/chesnay/flink/_build/results?buildId=1796
> [FLINK-25016] Upgrade Netty to 4.1.70

- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-36/pom.xml
- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-36/src/main/resources/META-INF/NOTICE
- flink-shaded-zookeeper-parent/pom.xml
Pretty similar to the current 3.5 module. Main difference is the ZK version (duh), and that we also bundle `io.dropwizard.metrics:metrics-core`.
A Flink build with the required changes can be seen here: https://dev.azure.com/chesnay/flink/_build/results?buildId=1850&view=results
> [FLINK-25145] Add Zookeeper 3.6

- flink-shaded-jackson-parent/flink-shaded-jackson-2/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-2/src/main/resources/META-INF/NOTICE
- flink-shaded-jackson-parent/flink-shaded-jackson-module-jsonSchema-2/pom.xml
- flink-shaded-jackson-parent/pom.xml
* Use the Jackson BOM
* Add Jackson jdk8 and javatime modules to the shaded jackson
Signed-off-by: slinkydeveloper <francescoguard@gmail.com>
> [FLINK-25588] Add Jackson JDK8 types to shaded jackson

- flink-shaded-jackson-parent/flink-shaded-jackson-2/src/main/resources/META-INF/NOTICE
- flink-shaded-jackson-parent/flink-shaded-jackson-module-jsonSchema-2/src/main/resources/META-INF/NOTICE
- pom.xml
Update of jackson-bom because of CVE-2022-42003
this was fixed within https://github.com/FasterXML/jackson-databind/issues/3590
> [FLINK-29631] Update Jackson-bom to 2.13.4.20221013

- flink-shaded-netty-tcnative-static/pom.xml
- flink-shaded-netty-tcnative-static/src/main/resources/META-INF/NOTICE
```
Nov 03 12:44:46 [INFO] --- maven-shade-plugin:3.1.1:shade (shade-flink) @ flink-shaded-netty-tcnative-static ---
Nov 03 12:44:47 [INFO] Including io.netty:netty-tcnative-boringssl-static:jar:2.0.54.Final in the shaded jar.
PROBLEM -> Nov 03 12:44:47 [INFO] Excluding io.netty:netty-tcnative-classes:jar:2.0.54.Final from the shaded jar.
Nov 03 12:44:47 [INFO] Including io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.54.Final in the shaded jar.
Nov 03 12:44:47 [INFO] Including io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.54.Final in the shaded jar.
Nov 03 12:44:47 [INFO] Including io.netty:netty-tcnative-boringssl-static:jar:osx-x86_64:2.0.54.Final in the shaded jar.
Nov 03 12:44:47 [INFO] Including …
```
> [FLINK-29889][netty] Bundle tcnative-classes

- README.md
The build should be done on a fresh checkout of the flink-shaded repository. Otherwise, we might run into errors in the jackson submodule:
```
$ mvn install -Dshade-sources
[...]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.1.1:shade (shade-flink) on project flink-shaded-jackson: Error creating shaded jar: duplicate entry: META-INF/services/org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.JsonFactory -> [Help 1]                                                            
[ERROR] …
```
> [hotfix][docs] Adds clean to Maven command in README file

- flink-shaded-asm-9/pom.xml
- flink-shaded-force-shading/pom.xml
- flink-shaded-guava-32/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-2/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jackson-module-jsonSchema-2/pom.xml
- flink-shaded-jackson-parent/pom.xml
- flink-shaded-netty-4/pom.xml
- flink-shaded-netty-tcnative-dynamic/pom.xml
- flink-shaded-netty-tcnative-static/pom.xml
- flink-shaded-swagger/pom.xml
- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-35/pom.xml
- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-36/pom.xml
- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-37/pom.xml
- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-38/pom.xml
- flink-shaded-zookeeper-parent/pom.xml
- pom.xml
Apply update to ~~18.0~~ 19.0 to master branch
cherry-pick of tagged commit https://github.com/apache/flink-shaded/commit/8ac82a30c48dd0221da24599e6b4a3c55583fd62
> [hotfix] Update version to 19.0

- flink-shaded-jackson-parent/flink-shaded-jsonpath/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jsonpath/src/main/resources/META-INF/NOTICE
- flink-shaded-jackson-parent/pom.xml
- pom.xml
We need a shaded version of `jsonpath` because we'd like to configure it with shaded versions of jackson in https://github.com/apache/flink/blob/27287a105f6585e89795e2a6cbffa8254abb6e57/flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/SqlJsonUtils.java#L76
I'm intentionally putting that under `jackson` even though it's not its subproject in order to apply the same jackson shading. After all this is the reason we shade jsonpath anyhow.
> [FLINK-35696] Shade com.jayway.jsonpath:json-path

- .github/workflows/ci.yml
- pom.xml
~~As a test [1] there was first a commit with enabling `ShadeOptionalChecker` however without adding `optional`. As a result it detects the issue i a number of places.~~
UPD: Since bumping version of flatten plugin helps I reverted changes (to not force push) and added version bump itself to 1.2.7
also keep a couple of hotfix commits as a result of review
> [FLINK-34234] Bumping version of flatten plugin to 1.2.7

- flink-shaded-jackson-parent/flink-shaded-jsonpath/pom.xml
- flink-shaded-jackson-parent/flink-shaded-jsonpath/src/main/resources/META-INF/NOTICE
- pom.xml
Update json-path library to address CVE-2023-1370 and CVE-2023-51074.
> [FLINK-33571] Update json-path to 2.9.0

- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-38/pom.xml
- flink-shaded-zookeeper-parent/flink-shaded-zookeeper-38/src/main/resources/META-INF/NOTICE
JIRA: FLINK-35003. Update zookeeper to 3.8.4 to address CVE-2024-23944.
From the maven link, we can know that CVE-2024-23944 exists in zookpeer-3.8.3, and we can upgrade to zookpeer-3.8.4 to solve this issue.
https://mvnrepository.com/artifact/org.apache.zookeeper/zookeeper/3.8.3
> [FLINK-35003] Update zookeeper to 3.8.4 to address CVE-2024-23944.
